# Generated by Django 4.2 on 2026-01-31 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_projectmanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150)),
                ('company_name', models.CharField(max_length=200)),
                ('client_image', models.ImageField(blank=True, null=True, upload_to='clients/')),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('project_name', models.CharField(max_length=200)),
                ('project_deadline', models.DateField()),
                ('project_status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('on-hold', 'On Hold')], max_length=20)),
                ('project_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('project_requirements', models.TextField()),
                ('requirement_document', models.FileField(blank=True, null=True, upload_to='client_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
